# .github/workflows/terraform.yml

name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: task_3

      - name: Terraform Validate
        run: terraform validate
        working-directory: task_3

      - name: Terraform Plan
        run: terraform plan
        working-directory: task_3

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: task_3